site_name: KC Gaming Encyclopedia
site_url: https://kcgamingencyclopedia.kierancollins.co.uk
repo_url: https://github.com/KC-OU/KC-Gaming-Encyclopedia
repo_name: KC-OU/KC-Gaming-Encyclopedia

# navigation
nav:
  - Home: 'index.md'
  - Bethesda:
     - Fallout 4:
  # TODO: add my own content / images to the pages
           - Game Overview: 'Bethesda/Fallout4/Game-Overview.md'
          
           # TODO: Need to create the pages
           - Stats:
                - SPECIAL: 'Bethesda/Fallout4/Stats/SPECIAL.md'
                - Perks: 'Bethesda/Fallout4/Stats/Perks.md'
                - Companion: 'Bethesda/Fallout4/Stats/Companion.md'
                - Combat: 'Bethesda/Fallout4/Stats/Combat.md'
# Theme config
theme:
    # Theme: https://squidfunk.github.io/mkdocs-material/
    name: material  
    features:
    # QOL features
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tabs.sticky
    - navigation.path
    - toc.follow 
    - navigation.indexes 
    - content.tooltips
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - content.code.annotate
    - announce.dismiss
    logo: assets/logo.png
    favicon: images/favicon.png
    font:
        text: Raleway
        code: Ubuntu Mono

  # //TODO: Need to change the fonts
    palette:
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: 'blue'
        accent: 'light blue'
        toggle:
            icon: material/brightness-4
            name: Toggle light mode
      - media: "(prefers-color-scheme: light)"
        scheme: light
        primary: 'blue'
        accent: 'light blue'
        toggle:
            icon: material/brightness-7
            name: Toggle dark mode
markdown_extensions:
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html 
  # - neoteroi.cards
